#ifndef SHAREDLIBRARYEXPORT_H
#define SHAREDLIBRARYEXPORT_H

#ifdef SHAREDLIBRARY_EXPORT
	#define SHAREDLIBRARY_API Q_DECL_EXPORT
#else
	#define SHAREDLIBRARY_API Q_DECL_IMPORT
#endif

#endif // SHAREDLIBRARYEXPORT_H
